#!/usr/bin/env node

/**
 * Generate Windmill MCP Server
 * 
 * This script generates the MCP server from the cached OpenAPI specification
 * using openapi-mcp-generator.
 */

import { spawn } from 'child_process';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load configuration
const configPath = path.join(__dirname, 'config.json');
let config;
try {
  const configData = await fs.readFile(configPath, 'utf-8');
  config = JSON.parse(configData);
} catch (error) {
  console.error('Error loading config:', error.message);
  process.exit(1);
}

const CACHE_PATH = path.resolve(__dirname, '..', config.openapi.localCache);
const OUTPUT_DIR = path.resolve(__dirname, '..', config.generator.outputDir);

/**
 * Check if openapi-mcp-generator is available
 */
async function checkGenerator() {
  return new Promise((resolve) => {
    const check = spawn('npx', ['openapi-mcp-generator', '--version'], {
      stdio: 'pipe'
    });
    
    check.on('close', (code) => {
      resolve(code === 0);
    });
    
    check.on('error', () => {
      resolve(false);
    });
  });
}

/**
 * Run command and return promise
 */
function runCommand(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    const proc = spawn(command, args, {
      stdio: 'inherit',
      ...options
    });
    
    proc.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Command failed with exit code ${code}`));
      }
    });
    
    proc.on('error', reject);
  });
}

/**
 * Main function
 */
async function main() {
  console.log('🚀 Starting Windmill MCP Server generation...\n');
  
  // Check if spec exists
  console.log('📋 Checking for OpenAPI specification...');
  try {
    await fs.access(CACHE_PATH);
    console.log(`✅ Found specification at ${CACHE_PATH}`);
  } catch {
    console.error('❌ OpenAPI specification not found!');
    console.error('   Run "npm run fetch-spec" first');
    process.exit(1);
  }
  
  // Check generator availability
  console.log('\n🔧 Checking openapi-mcp-generator...');
  const generatorAvailable = await checkGenerator();
  if (!generatorAvailable) {
    console.log('⚠️  openapi-mcp-generator not found, installing...');
    console.log('   Note: This is a placeholder. The actual generator needs to be installed separately.');
    console.log('   Please visit: https://github.com/harsha-iiiv/openapi-mcp-generator');
    console.log('\n📝 For now, creating a basic MCP server structure...');
  }
  
  // Create output directory
  console.log(`\n📁 Creating output directory: ${OUTPUT_DIR}`);
  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  
  // Generate basic MCP server structure
  console.log('\n⚙️  Generating MCP server structure...');
  
  // Read the OpenAPI spec to get info
  const specContent = await fs.readFile(CACHE_PATH, 'utf-8');
  const spec = JSON.parse(specContent);
  
  // Create a basic index.js
  const indexContent = `#!/usr/bin/env node

/**
 * Windmill MCP Server
 * Generated from OpenAPI specification
 * Version: ${spec.info.version || 'unknown'}
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

// This is a placeholder implementation
// The actual implementation should be generated by openapi-mcp-generator

const server = new Server(
  {
    name: 'windmill-mcp',
    version: '${spec.info.version || '0.1.0'}',
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// List available tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: 'placeholder',
        description: 'Placeholder tool - actual tools should be generated from OpenAPI spec',
        inputSchema: {
          type: 'object',
          properties: {},
        },
      },
    ],
  };
});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  throw new Error('Tool execution not yet implemented - needs openapi-mcp-generator integration');
});

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('Windmill MCP server running on stdio');
}

main().catch(console.error);
`;
  
  await fs.writeFile(path.join(OUTPUT_DIR, 'index.js'), indexContent);
  
  console.log('✅ Basic server structure created');
  console.log('\n⚠️  Important: This is a placeholder structure!');
  console.log('   To generate the full MCP server:');
  console.log('   1. Install openapi-mcp-generator');
  console.log('   2. Update this script to use the generator');
  console.log('   3. Re-run npm run generate');
  
  // Apply overrides if configured
  if (config.postGeneration.applyOverrides) {
    console.log('\n🔄 Post-generation: Applying overrides...');
    try {
      await runCommand('npm', ['run', 'apply-overrides']);
    } catch (error) {
      console.warn('⚠️  Override application failed (may not exist yet)');
    }
  }
  
  console.log('\n✨ Generation complete!');
  console.log(`   Output: ${OUTPUT_DIR}`);
  console.log('\n📝 Next steps:');
  console.log('   1. Review generated files in src/');
  console.log('   2. Add customizations in overrides/');
  console.log('   3. Run tests: npm test');
}

// Run main function
main().catch((error) => {
  console.error('Generation failed:', error);
  process.exit(1);
});
