ls:
  # Root directory - specific uppercase files allowed
  .js: regex:^vitest\.config$
  .json: regex:^package$
  .yml: regex:^\.ls-lint$
  .md: regex:^(README|CHANGELOG|CONTRIBUTING|PROJECT_STATUS|AGENTS)$
  .example: regex:^\.env$
  .ignore: regex:^(\.gitignore|\.npmignore)$
  .dir: regex:^([a-z][a-z0-9-]*|\.github|\.husky)$ # kebab-case or conventional dot-directories

  # GitHub workflows
  .github/workflows:
    .yml: kebab-case
    .yaml: kebab-case
    .md: regex:^(README|AGENTS)$

  # Source directories
  src:
    .dir: kebab-case
    .js: kebab-case
    .ts: kebab-case
    .json: kebab-case
    .md: regex:^([a-z][a-z0-9-]*|README|AGENTS)$

  # Test directories
  tests:
    .dir: kebab-case
    .js: kebab-case
    .ts: kebab-case
    .json: kebab-case
    .md: regex:^([a-z][a-z0-9-]*|README|AGENTS)$

  # Documentation (allow CONTRIBUTING in addition to README/AGENTS)
  docs:
    .dir: kebab-case
    .md: regex:^([a-z][a-z0-9-]*|README|CONTRIBUTING|AGENTS)$

ignore:
  - .git
  - .husky/_ # Husky internal directory
  - node_modules
  - dist
  - build
  - cache
  - coverage
  - .DS_Store
  - .env
  - .env.local
  - package-lock.json
  - npm-debug.log
