#!/usr/bin/env node

/**
 * Windmill MCP Server
 * Generated from OpenAPI specification
 * Version: 1.520.1
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { config } from 'dotenv';

// Load environment variables
config();

// This is a basic implementation with core Windmill API tools
// Full implementation should be generated by openapi-mcp-generator

const WINDMILL_BASE_URL = process.env.WINDMILL_BASE_URL || process.env.E2E_WINDMILL_URL || 'http://localhost:8000';
const WINDMILL_TOKEN = process.env.WINDMILL_API_TOKEN || process.env.E2E_WINDMILL_TOKEN;

/**
 * Make a request to Windmill API
 */
async function callWindmillAPI(endpoint, options = {}) {
  const url = `${WINDMILL_BASE_URL}${endpoint}`;
  const headers = {
    'Content-Type': 'application/json',
    ...options.headers,
  };
  
  if (WINDMILL_TOKEN) {
    headers['Authorization'] = `Bearer ${WINDMILL_TOKEN}`;
  }
  
  const response = await fetch(url, {
    ...options,
    headers,
  });
  
  if (!response.ok) {
    throw new Error(`Windmill API error: ${response.status} ${response.statusText}`);
  }
  
  return response.json();
}

const server = new Server(
  {
    name: 'windmill-mcp',
    version: '1.520.1',
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// List available tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: 'list_jobs',
        description: 'List all jobs in a workspace',
        inputSchema: {
          type: 'object',
          properties: {
            workspace: {
              type: 'string',
              description: 'The workspace ID',
            },
          },
          required: ['workspace'],
        },
      },
      {
        name: 'get_job',
        description: 'Get details of a specific job',
        inputSchema: {
          type: 'object',
          properties: {
            workspace: {
              type: 'string',
              description: 'The workspace ID',
            },
            job_id: {
              type: 'string',
              description: 'The job ID',
            },
          },
          required: ['workspace', 'job_id'],
        },
      },
      {
        name: 'list_scripts',
        description: 'List all scripts in a workspace',
        inputSchema: {
          type: 'object',
          properties: {
            workspace: {
              type: 'string',
              description: 'The workspace ID',
            },
          },
          required: ['workspace'],
        },
      },
      {
        name: 'list_workflows',
        description: 'List all workflows in a workspace',
        inputSchema: {
          type: 'object',
          properties: {
            workspace: {
              type: 'string',
              description: 'The workspace ID',
            },
          },
          required: ['workspace'],
        },
      },
      {
        name: 'get_version',
        description: 'Get Windmill server version',
        inputSchema: {
          type: 'object',
          properties: {},
        },
      },
    ],
  };
});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  
  try {
    let result;
    
    switch (name) {
      case 'list_jobs':
        result = await callWindmillAPI(`/api/w/${args.workspace}/jobs/list`);
        break;
        
      case 'get_job':
        result = await callWindmillAPI(`/api/w/${args.workspace}/jobs/get/${args.job_id}`);
        break;
        
      case 'list_scripts':
        result = await callWindmillAPI(`/api/w/${args.workspace}/scripts/list`);
        break;
        
      case 'list_workflows':
        result = await callWindmillAPI(`/api/w/${args.workspace}/flows/list`);
        break;
        
      case 'get_version':
        result = await callWindmillAPI('/api/version');
        break;
        
      default:
        throw new Error(`Unknown tool: ${name}`);
    }
    
    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify(result, null, 2),
        },
      ],
    };
  } catch (error) {
    return {
      content: [
        {
          type: 'text',
          text: `Error: ${error.message}`,
        },
      ],
      isError: true,
    };
  }
});

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('Windmill MCP server running on stdio');
}

main().catch(console.error);
